const cities_with_code = {
    "Cairo": "01",
    "Alexandria": "02",
    "Port Said": "03",
    "Suez": "04",
    "Ismailia": "11",
    "Kafr El Sheikh": "12",
    "Gharbia": "13",
    "Monufia": "14",
    "Dakahlia": "15",
    "Damietta": "16",
    "Sharqia": "17",
    "North Sinai": "18",
    "South Sinai": "19",
    "Faiyum": "21",
    "Minya": "22",
    "Beni Suef": "23",
    "Asyut": "24",
    "New Valley": "25",
    "Sohag": "26",
    "Qena": "27",
    "Luxor": "28",
    "Aswan": "29",
    "Red Sea": "31",
    "Beheira": "32",
    "Helwan": "33",
    "Giza": "21"
}
const cities = [
    "Cairo",
    "Alexandria",
    "Port Said",
    "Suez",
    "Ismailia",
    "Kafr El Sheikh",
    "Gharbia",
    "Monufia",
    "Dakahlia",
    "Damietta",
    "Sharqia",
    "North Sinai",
    "South Sinai",
    "Faiyum",
    "Minya",
    "Beni Suef",
    "Asyut",
    "New Valley",
    "Sohag",
    "Qena",
    "Luxor",
    "Aswan",
    "Red Sea",
    "Beheira",
    "Helwan",
    "Giza"
]
const code_with_cities = {
    "01": "Cairo",
    "02": "Alexandria",
    "03": "Port Said",
    "04": "Suez",
    "11": "Ismailia",
    "12": "Kafr El Sheikh",
    "13": "Gharbia",
    "14": "Monufia",
    "15": "Dakahlia",
    "16": "Damietta",
    "17": "Sharqia",
    "18": "North Sinai",
    "19": "South Sinai",
    "21": "Faiyum",
    "22": "Minya",
    "23": "Beni Suef",
    "24": "Asyut",
    "25": "New Valley",
    "26": "Sohag",
    "27": "Qena",
    "28": "Luxor",
    "29": "Aswan",
    "31": "Red Sea",
    "32": "Beheira",
    "33": "Helwan",
    "21": "Giza"
}

module.exports = {cities, cities_with_code, code_with_cities}

/*
https://codereview.stackexchange.com/questions/221899/extract-information-from-egyptian-national-id
 */